networks:
  opentelemetry:
    name: opentelemetry
    driver: bridge
#    external: true

services:
  tomcat-test:
    image: curlimages/curl
    networks:
      - opentelemetry
#    ports:
#      - 8090
    command: ["curl", "http://tomcat:8080"]
