networks:
  opentelemetry:
    name: opentelemetry
    driver: bridge

services:
  tomcat-test:
    image: curlimages/curl
    networks:
      - opentelemetry
    command: ["curl", "http://tomcat:8080"]
