receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlphttp/dynatrace:  
    endpoint: "${env:DT_ENDPOINT}"  
    headers:  
      Authorization: "Api-Token ${env:DT_API_TOKEN}" 
  environment:
    - DT_ENDPOINT 
    - DT_API_TOKEN
      
service:
  pipelines:
    traces/dynatrace:  
      receivers: [otlp]  
      processors: []  
      exporters: [otlphttp/dynatrace]  
    metrics/dynatrace:  
      receivers: [otlp]  
      processors: [cumulativetodelta]  
      exporters: [otlphttp/dynatrace]  
    logs/dynatrace:  
      receivers: [otlp]  
      processors: []  
      exporters: [otlphttp/dynatrace]
  telemetry:
    logs:
      level: info
