# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"
    tag: "{{.Name}}"
    
networks:
  opentelemetry:
    name: opentelemetry
    driver: bridge
    external: true

services:

  # ********************
  # Telemetry Components
  # ********************
  # Jaeger
  jaeger:
    image: ${JAEGER_IMAGE}
    container_name: jaeger
    command:
      - "--config=file:/etc/jaeger/config.yml"
    networks:
      - ${NETWORK_NAME}
    deploy:
      resources:
        limits:
          memory: ${JAEGER_MEMORY_LIMIT}
    restart: unless-stopped
    ports:
      - "${JAEGER_UI_PORT}:${JAEGER_UI_PORT}"
      - "${JAEGER_GRPC_PORT}:${JAEGER_GRPC_PORT}"
      - "${JAEGER_HTTP_PORT}:${JAEGER_HTTP_PORT}"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - JAEGER_UI_PORT
      - JAEGER_GRPC_PORT
      - JAEGER_HTTP_PORT
      - MEMORY_MAX_TRACES=25000
      - SPAN_STORAGE_TYPE=memory
    volumes:
      - ./src/jaeger/config.yml:/etc/jaeger/config.yml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:16686 || exit 1"]  # Checks Jaeger UI readiness
      start_period: 30s
      interval: 10s
      timeout: 5s
      retries: 5
    logging: *logging

  # Grafana
  grafana:
    image: ${GRAFANA_IMAGE}
    container_name: grafana
    networks:
      - ${NETWORK_NAME}
    deploy:
      resources:
        limits:
          memory: 120M
    restart: unless-stopped
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true          # dev only!
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./src/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./src/grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    logging: *logging

  # OpenTelemetry Collector
  otel-collector:
    image: ${COLLECTOR_CONTRIB_IMAGE}
    container_name: otel-collector
    networks:
      - ${NETWORK_NAME}
    deploy:
      resources:
        limits:
          memory: 200M
    restart: unless-stopped
    command: [ "--config=/etc/otelcol-config.yml", "--config=/etc/otelcol-config-extras.yml" ]
    user: 0:0
    volumes:
      - ${HOST_FILESYSTEM}:/hostfs:ro
      - ${DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${OTEL_COLLECTOR_CONFIG}:/etc/otelcol-config.yml
      - ${OTEL_COLLECTOR_CONFIG_EXTRAS}:/etc/otelcol-config-extras.yml
    ports:
      - "${OTEL_COLLECTOR_PORT_OTLP_GRPC}:${OTEL_COLLECTOR_PORT_OTLP_GRPC}"
      - "${OTEL_COLLECTOR_PORT_OTLP_HTTP}:${OTEL_COLLECTOR_PORT_OTLP_HTTP}"
    logging: *logging
    environment:
      - HOST_FILESYSTEM
      - OTEL_COLLECTOR_HOST
      - OTEL_COLLECTOR_PORT_GRPC
      - OTEL_COLLECTOR_PORT_HTTP
  depends_on:
      jaeger:
        condition: service_started
      prometheus:
        condition: service_healthy

  # Prometheus
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    container_name: prometheus
    command:
      - --web.console.templates=/etc/prometheus/consoles
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
      - --web.route-prefix=/
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./src/prometheus/prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    networks:
      - opentelemetry
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    logging: *logging

  # OpenSearch
  opensearch:
    container_name: opensearch
    build:
      context: ./
      dockerfile: ${OPENSEARCH_DOCKERFILE}
      cache_from:
        - ${IMAGE_NAME}:${IMAGE_VERSION}-opensearch
    networks:
      - opentelemetry
    deploy:
      resources:
        limits:
          memory: 800M
    restart: unless-stopped
    environment:
      - cluster.name=demo-cluster
      - node.name=demo-node
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms400m -Xmx400m
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - DISABLE_SECURITY_PLUGIN=true
      # Workaround on OSX for https://bugs.openjdk.org/browse/JDK-8345296
      - _JAVA_OPTIONS
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "${OPENSEARCH_PORT}:${OPENSEARCH_PORT}"
    healthcheck:
      test: curl -s http://localhost:9200/_cluster/health | grep -E '"status":"(green|yellow)"'
      start_period: 10s
      interval: 5s
      timeout: 10s
      retries: 10
    logging: *logging
