services:
  # OpenTelemetry Collector
  otel-collector:
    image: ${OTEL_COLLECTOR_IMAGE}
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./src/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "${OTEL_COLLECTOR_PORT_OTLP_GRPC}:4317"      # OTLP gRPC
      - "${OTEL_COLLECTOR_PORT_OTLP_HTTP}:4318"     # OTLP HTTP
      - "${OTEL_COLLECTOR_PORT_METRICS}:8888"       # Prometheus metrics endpoint
      - "${OTEL_COLLECTOR_PORT_DEBUG}:13133"        # health_check extension
    depends_on:
      - jaeger
      - prometheus
    environment:
      - JAEGER_ENDPOINT=http://jaeger:14250
      - PROMETHEUS_ENDPOINT=http://prometheus:9090

  # Jaeger (all-in-one: collector + query + UI)
  jaeger:
    image: ${JAEGERTRACING_IMAGE}
    restart: unless-stopped
    ports:
      - "${JAEGER_QUERY_PORT}:16686"          # Jaeger UI
      - "${JAEGER_COLLECTOR_OTLP_PORT}:4317" # OTLP gRPC (collector)
      - "${JAEGER_COLLECTOR_OTLP_HTTP_PORT}:4318" # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - MEMORY_MAX_TRACES=50000
      - SPAN_STORAGE_TYPE=memory
      - MEM_LIMIT=${JAEGER_MEMORY_LIMIT}

  # Prometheus
  prometheus:
    image: ${PROMETHEUS_IMAGE}
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./src/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"

  # Grafana
  grafana:
    image: ${GRAFANA_IMAGE}
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./src/grafana-provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true          # dev only!
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - prometheus
      - jaeger

volumes:
  prometheus_data:
  grafana_data:
